### ISSUE TITLE
Error in Qgis 3.22.1 

### ISSUE THREAD

**Issue by smblnts21** [havatv/qgisnnjoinplugin#30]
File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NNJoin/NNJoin_plugin.py", line 137, in run
              self.dlg.progressBar.setValue(int(0.0))
             TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by LJ16** [comment]
Hi
i have a similar problem !

LJ

**Comment by LJ16** [comment]
Impossible de charger l'extension 'NNJoin' provoque une erreur lors de l'appel à sa méthode classFactory() 

SyntaxError: invalid character '·' (U+00B7) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/laurent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NNJoin/__init__.py", line 38, in classFactory
    from .NNJoin_plugin import NNJoin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NNJoin/NNJoin_plugin.py", line 65
    
                                                       ^
SyntaxError: invalid character '·' (U+00B7)


Version de Python : 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] 
Version de QGIS : 3.22.4-Białowieża Białowieża, exported

**Comment by LJ16** [comment]
Hi
have you a issue ? LJ

**Comment by raymondnijssen** [comment]
duplicate #32
