### ISSUE TITLE
ModuleNotFoundError: No module named 'qgisnnjoinplugin-master.resources' 

### ISSUE THREAD

**Issue by jikac** [havatv/qgisnnjoinplugin#36]
Installing this plugin from the zip file produces the following:

```
Couldn't load plugin 'qgisnnjoinplugin-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'qgisnnjoinplugin-master.resources' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisnnjoinplugin-master/__init__.py", line 38, in classFactory
    from .NNJoin_plugin import NNJoin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgisnnjoinplugin-master/NNJoin_plugin.py", line 43, in 
    from .resources import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgisnnjoinplugin-master.resources'


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.34.1-Prizren Prizren, 133927424d9 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jikaczmarski/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
```

**Comment by jikac** [comment]
Replicated on Python 3.11.2:

```
Couldn't load plugin 'qgisnnjoinplugin-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'qgisnnjoinplugin-master.resources' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisnnjoinplugin-master/__init__.py", line 38, in classFactory
    from .NNJoin_plugin import NNJoin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisnnjoinplugin-master/NNJoin_plugin.py", line 43, in 
    from .resources import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'qgisnnjoinplugin-master.resources'


Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] 
QGIS version: 3.34.2-Prizren Prizren, 7d199797fcc 

Python Path:
/usr/share/qgis/python
/home/jesse/.local/share/QGIS/QGIS3/profiles/default/python
/home/jesse/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python311.zip
/usr/lib/python3.11
/usr/lib/python3.11/lib-dynload
/usr/local/lib/python3.11/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.11/dist-packages
/home/jesse/.local/share/QGIS/QGIS3/profiles/default/python
/home/jesse/acep/git-repos/geocoding/pii-data/gis-geocoding
```
