### ISSUE TITLE
NNJoin issue

### ISSUE THREAD

**Issue by SimoneLioy** [havatv/qgisnnjoinplugin#39]
NNJoin does not work on QGIS 3.34 and 3.40.

Heafter the error detalis from the python console:

_Traceback (most recent call last):
File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_plugin.py", line 137, in run
 self.dlg.progressBar.setValue(0.0)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'_

Tried to fix the error with the following solution: https://gis.stackexchange.com/questions/439177/nnjoin-not-returning-any-result
After the changes, NNJoin open but after executing it QGIS crashes. Hearafter the crash report of QGis 3.40:

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000064c0 (most recent call first):
  File "C:\Users/memno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_gui.py", line 585 in showError
    self.iface.messageBar().pushMessage(self.tr('Error'), text,
  File "C:\Users/memno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_gui.py", line 221 in workerFinished
    self.showError(self.tr('Aborted') + '!')
  File "C:\Users/memno/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_plugin.py", line 177 in run
    self.dlg.exec_()
```

**Stack Trace**

```

QVariantAnimation::endValue :
QFocusFrame::tr :
QToolBar::widgetForAction :
QTabBarPrivate::~QTabBarPrivate :
QTabBarPrivate::isAnimated :
QLayoutPrivate::doResize :
QLayout::activate :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QgsMessageBar::showItem :
QgsMessageBar::pushItem :
QgsMessageBar::pushMessage :
QgsPresetSchemeColorRamp::clone :
PyLong_FromString :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyArg_CheckPositional :
PyObject_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyLong_FromString :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyArg_CheckPositional :
PyObject_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.40.1-Bratislava
QGIS code revision: 989853a7
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.3
Running against GDAL: 3.9.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

**Comment by AstroSmile** [comment]
Problem solved for more recent versions of QGIS 3.34 and 3.40

The error in question occurred when running the nnjoin plugin:

_Traceback (most recent call last):
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\user/python/plugins\NNJoin\NNJoin_plugin.py", line 137, in run
              self.dlg.progressBar.setValue(0.0)
             TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'_

The solution is to look for the file: NNJoin_plugin.py in the indicated path and modify the line that is giving us an error, since it expects a decimal input when it should be an integer.

We look for the line of code: self.dlg.progressBar.setValue(0.0) and replace it with self.dlg.progressBar.setValue(0). 

Once the change is made, we save the file with the modification. We open QGIS again and run the nnjoin plugin again, but this time without errors.

**Comment by bornaqua** [comment]
Unfortunately, it's not complete.
After following your steps and trying to use nnjoin, I got a new error message:
“...python/plugins\NNJoin\NNJoin_plugin.py”, line 177 in run self.dlg.exec_()

See also SimonieLioy.

Do you have any other ideas?

**Comment by AstroSmile** [comment]
The NNJoin QGIS plugin errors because it crashes while trying to open its graphical window (PyQt dialog using modal exec_()). The issue is in the visual UI, not the spatial operation.
Fix: Run QGIS as admin or edit the plugin and replace:

self.dlg.exec_()

For this:

self.dlg.show()
return

Save and restart QGIS. Plugin-free option (no graphical window): Processing → “Join attributes by nearest” (Neighbors = 1).
